(function(){"use strict";
const levels=[{code:"A",name:"Émergent",score:1,description:"Les pratiques sont ponctuelles, informelles et principalement réactives."},{code:"B",name:"En progression",score:2,description:"Des pratiques existent mais elles sont encore partielles, hétérogènes ou peu coordonnées."},{code:"C",name:"Établi",score:3,description:"Les pratiques sont formalisées, déployées et appliquées de manière généralement cohérente."},{code:"D",name:"Avancé",score:4,description:"Les pratiques sont intégrées au pilotage, mesurées et régulièrement améliorées."},{code:"E",name:"Aspirationnel",score:5,description:"Les pratiques sont pleinement intégrées, prédictives et continuellement optimisées."}];
const definitions=[
["strategie","Stratégie",8,["La gestion des risques est-elle intégrée aux objectifs et aux décisions stratégiques ?","L’appétence et les seuils de tolérance aux risques sont-ils définis et approuvés ?","Les évolutions externes sont-elles intégrées à l’analyse des risques stratégiques ?"]],
["gouvernance","Gouvernance",12,["Les rôles et responsabilités de gestion des risques sont-ils clairement définis ?","Les instances dirigeantes examinent-elles régulièrement les risques majeurs ?","Le dispositif fait-il l’objet d’une supervision indépendante et documentée ?"]],
["culture","Culture",8,["Les collaborateurs comprennent-ils leur rôle dans la maîtrise des risques ?","La direction favorise-t-elle une communication ouverte sur les incidents et vulnérabilités ?","La prise en compte des risques est-elle intégrée aux objectifs et aux comportements ?"]],
["identification","Identification des risques",10,["Un processus structuré permet-il d’identifier les risques dans tout le périmètre ?","Les risques émergents et les interdépendances sont-ils systématiquement recherchés ?","Le registre des risques est-il complet, actualisé et attribué à des responsables ?"]],
["analyse","Analyse et évaluation",10,["Les risques sont-ils évalués selon des critères communs de probabilité et d’impact ?","Les contrôles existants et leur efficacité sont-ils pris en compte dans l’évaluation ?","Des scénarios et analyses quantitatives complètent-ils les appréciations qualitatives ?"]],
["traitement","Traitement des risques",10,["Chaque risque significatif dispose-t-il d’une stratégie de traitement formalisée ?","Les plans d’action comportent-ils responsables, échéances et ressources ?","L’efficacité des mesures de traitement est-elle suivie et réévaluée ?"]],
["revue","Revue et révision",7,["Le profil de risque est-il revu à une fréquence définie et après tout changement majeur ?","Les incidents et quasi-incidents alimentent-ils l’amélioration du dispositif ?","Des indicateurs mesurent-ils la performance et la maturité de la gestion des risques ?"]],
["reporting","Information et reporting",7,["Les informations sur les risques sont-elles fiables, accessibles et diffusées à temps ?","Le reporting est-il adapté aux besoins des différentes instances de décision ?","Des indicateurs d’alerte permettent-ils de détecter rapidement les dépassements de seuils ?"]],
["continuite","Continuité d’activité",12,["Les activités critiques et leurs besoins de reprise sont-ils identifiés ?","Les plans de continuité et de reprise sont-ils documentés, maintenus et testés ?","Les dépendances aux fournisseurs et ressources clés sont-elles couvertes par les plans ?"]],
["crise","Gestion de crise",10,["Une organisation de crise avec rôles, procédures et moyens est-elle formalisée ?","Les équipes de crise sont-elles formées et entraînées au moyen d’exercices réguliers ?","La communication de crise couvre-t-elle les parties prenantes internes et externes ?"]],
["resilience","Résilience organisationnelle",6,["L’organisation coordonne-t-elle risques, continuité, crise et sécurité dans une approche intégrée ?","Les enseignements des perturbations sont-ils transformés en améliorations durables ?","La capacité d’adaptation de l’organisation est-elle évaluée face à des scénarios sévères ?"]]
];
const shortActions={strategie:"Aligner l’appétence au risque et les arbitrages stratégiques.",gouvernance:"Clarifier les responsabilités et renforcer la supervision.",culture:"Développer les compétences et la culture du signalement.",identification:"Fiabiliser le registre et la veille sur les risques émergents.",analyse:"Harmoniser les méthodes d’évaluation et les scénarios.",traitement:"Prioriser et piloter les plans de traitement.",revue:"Installer une revue périodique et des indicateurs de performance.",reporting:"Adapter les tableaux de bord aux décisions attendues.",continuite:"Actualiser et tester les plans de continuité.",crise:"Formaliser et exercer le dispositif de crise.",resilience:"Intégrer les disciplines de résilience et capitaliser les retours d’expérience."};
const dimensions=definitions.map((d,index)=>({id:d[0],name:d[1],weight:d[2],order:index,recommendations:Object.fromEntries(levels.map(l=>[l.name,{diagnostic:`Le niveau ${l.name.toLowerCase()} indique que la dimension « ${d[1]} » ${l.score<3?"nécessite une structuration prioritaire":l.score<5?"dispose de bases solides à consolider":"constitue une pratique de référence à maintenir"}.`,shortTerm:l.score<4?shortActions[d[0]]:"Préserver les acquis, mesurer leur efficacité et traiter les écarts résiduels.",mediumTerm:l.score<3?"Formaliser une feuille de route, des responsables, des indicateurs et un cycle de revue.":"Renforcer l’automatisation, l’analyse prospective et l’amélioration continue."}]))}));
let n=0;const questions=definitions.flatMap(d=>d[3].map(text=>({id:++n,dimensionId:d[0],text,answers:levels.map(x=>({...x}))})));
window.FINASURE_ERM_DATA=Object.freeze({version:"2026.1-fallback",sourceStatus:"Classeur Excel absent — contenu métier de remplacement",levels,dimensions,questions,steps:[[1,5],[6,10],[11,15],[16,20],[21,25],[26,30],[31,33]],contactUrl:"https://www.finasure-solutions.com/contact/"});})();
