(function(){
"use strict";
const page=document.body.dataset.page, titles={dashboard:"Tableau de bord",companies:"Entreprises",company:"Fiche entreprise",assessments:"Évaluations",assessment:"Détail de l’évaluation",reports:"Rapports",appointments:"Rendez-vous",activity:"Historique",settings:"Paramètres"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=v=>v?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const score=v=>Number.isFinite(Number(v))?Number(v).toFixed(2).replace(".",","):"—";
const badge=v=>`<span class="badge">${esc(v||"—")}</span>`;
const params=()=>new URLSearchParams(location.search);
function table(headers,rows){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")||`<tr><td colspan="${headers.length}" class="empty">Aucune donnée disponible.</td></tr>`}</tbody></table></div>`}
function stat(label,value){return `<article class="kpi"><small>${label}</small><strong>${esc(value)}</strong></article>`}
function error(content,e){content.innerHTML=`<div class="error-box"><strong>Impossible de charger les données.</strong><br>${esc(e.message)}</div>`}
function pagination(container,current,total,pageSize,reload){const pages=Math.max(1,Math.ceil(total/pageSize));container.insertAdjacentHTML("beforeend",`<div class="pagination"><button class="btn btn-light" data-prev ${current<=1?"disabled":""}>Précédent</button><span>Page ${current} / ${pages}</span><button class="btn btn-light" data-next ${current>=pages?"disabled":""}>Suivant</button></div>`);container.querySelector("[data-prev]").onclick=()=>reload(current-1);container.querySelector("[data-next]").onclick=()=>reload(current+1)}
function radarAverages(rows){const grouped={};rows.forEach(x=>(grouped[x.dimension_name]??=[]).push(Number(x.score)));return Object.entries(grouped).map(([name,v])=>({name,value:v.reduce((a,b)=>a+b,0)/v.length}))}
async function dashboard(c){const d=await AdminApi.dashboard(),avg=d.assessments.length?d.assessments.reduce((s,x)=>s+Number(x.global_score||0),0)/d.assessments.length:0;c.innerHTML=`<section class="kpi-grid">${stat("Entreprises",d.companyCount)}${stat("Évaluations terminées",d.assessments.length)}${stat("Score moyen",score(avg)+" / 5")}${stat("Rendez-vous demandés",d.appointments.length)}</section><section class="grid-2"><article class="card"><h2>Évaluations dans le temps</h2><div class="chart-wrap"><canvas id="trend"></canvas></div></article><article class="card"><h2>Maturité moyenne par dimension</h2><div class="chart-wrap"><canvas id="radar"></canvas></div></article></section><article class="card"><h2>Dernières évaluations</h2>${table(["Entreprise","Score","Niveau","Date"],d.assessments.slice(0,8).map(x=>`<tr><td>${esc(x.companies?.name)}</td><td>${score(x.global_score)} / 5</td><td>${badge(x.global_level)}</td><td>${date(x.completed_at)}</td></tr>`))}</article>`;
const chrono=[...d.assessments].reverse();new Chart(document.querySelector("#trend"),{type:"line",data:{labels:chrono.map(x=>new Date(x.completed_at).toLocaleDateString("fr-FR")),datasets:[{label:"Score",data:chrono.map(x=>x.global_score),borderColor:"#25a9e0",backgroundColor:"rgba(37,169,224,.12)",fill:true,tension:.3}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{min:1,max:5}}}});
const r=radarAverages(d.dimensions);new Chart(document.querySelector("#radar"),{type:"radar",data:{labels:r.map(x=>x.name),datasets:[{label:"Score moyen",data:r.map(x=>x.value),borderColor:"#25a9e0",backgroundColor:"rgba(37,169,224,.18)"}]},options:{responsive:true,maintainAspectRatio:false,scales:{r:{min:0,max:5}}}})}
async function companies(c){c.innerHTML=`<article class="card"><form id="filters" class="filters"><input name="search" placeholder="Rechercher une entreprise"><select name="sector"><option value="">Tous les secteurs</option><option>Assurance</option><option>Banque</option><option>Industrie</option><option>Services</option><option>Énergie</option></select><button class="btn">Filtrer</button></form><div id="list"></div></article>`;const load=async(p=1)=>{const f=new FormData(c.querySelector("#filters")),size=15,d=await AdminApi.companies({search:f.get("search"),sector:f.get("sector"),from:(p-1)*size,to:p*size-1}),list=c.querySelector("#list");list.innerHTML=table(["Entreprise","Secteur","Effectif","Répondants","Dernier score","Date"],d.data.map(x=>{const a=[...(x.assessments||[])].sort((a,b)=>new Date(b.completed_at)-new Date(a.completed_at))[0];return `<tr><td><a href="entreprise.html?id=${encodeURIComponent(x.id)}">${esc(x.name)}</a></td><td>${esc(x.sector||"—")}</td><td>${esc(x.workforce||"—")}</td><td>${x.respondents?.length||0}</td><td>${score(a?.global_score)}</td><td>${date(a?.completed_at)}</td></tr>`}));pagination(list,p,d.count||0,size,load)};c.querySelector("#filters").onsubmit=e=>{e.preventDefault();load()};await load()}
async function company(c){const d=await AdminApi.company(params().get("id"));c.innerHTML=`<article class="card"><h2>${esc(d.name)}</h2><div class="detail-grid"><div class="detail-item"><small>Secteur</small>${esc(d.sector||"—")}</div><div class="detail-item"><small>Effectif</small>${esc(d.workforce||"—")}</div><div class="detail-item"><small>Périmètre</small>${esc(d.scope||"—")}</div></div></article><article class="card"><h2>Répondants</h2>${table(["Nom","Fonction","E-mail","Téléphone"],(d.respondents||[]).map(x=>`<tr><td>${esc(x.first_name)} ${esc(x.last_name)}</td><td>${esc(x.job_title||"—")}</td><td>${esc(x.email)}</td><td>${esc(x.phone||"—")}</td></tr>`))}</article><article class="card"><h2>Historique des évaluations</h2>${table(["Score","Niveau","Date","Rapport","Action"],(d.assessments||[]).map(x=>`<tr><td>${score(x.global_score)} / 5</td><td>${badge(x.global_level)}</td><td>${date(x.completed_at)}</td><td>${x.reports?.length?badge("Demandé"):"—"}</td><td><a href="evaluation.html?id=${x.id}">Consulter</a></td></tr>`))}</article>`}
async function assessments(c){c.innerHTML=`<article class="card"><form id="filters" class="filters"><select name="level"><option value="">Tous niveaux</option><option>Initial</option><option>Émergent</option><option>Structuré</option><option>Maîtrisé</option><option>Optimisé</option></select><input type="date" name="fromDate"><input type="date" name="toDate"><button class="btn">Filtrer</button></form><div id="list"></div></article>`;const load=async(p=1)=>{const f=new FormData(c.querySelector("#filters")),size=15,d=await AdminApi.assessments({level:f.get("level"),fromDate:f.get("fromDate"),toDate:f.get("toDate"),from:(p-1)*size,to:p*size-1}),list=c.querySelector("#list");list.innerHTML=table(["Entreprise","Répondant","Score","Niveau","Date","Action"],d.data.map(x=>`<tr><td>${esc(x.companies?.name)}</td><td>${esc(x.respondents?.first_name)} ${esc(x.respondents?.last_name)}</td><td>${score(x.global_score)} / 5</td><td>${badge(x.global_level)}</td><td>${date(x.completed_at)}</td><td><a href="evaluation.html?id=${x.id}">Voir</a></td></tr>`));pagination(list,p,d.count||0,size,load)};c.querySelector("#filters").onsubmit=e=>{e.preventDefault();load()};await load()}
async function assessment(c){const d=await AdminApi.assessment(params().get("id")),dims=d.dimension_scores||[];c.innerHTML=`<section class="kpi-grid">${stat("Entreprise",d.companies?.name)}${stat("Répondant",`${d.respondents?.first_name||""} ${d.respondents?.last_name||""}`)}${stat("Score global",score(d.global_score)+" / 5")}${stat("Niveau",d.global_level)}</section><section class="grid-2"><article class="card"><h2>Scores par dimension</h2>${dims.map(x=>`<p><strong>${esc(x.dimension_name)}</strong> — ${score(x.score)} / 5</p><div class="score-bar"><i style="width:${Math.min(100,Number(x.score)*20)}%"></i></div>`).join("")}</article><article class="card"><h2>Radar</h2><div class="chart-wrap"><canvas id="detailRadar"></canvas></div></article></section><article class="card"><h2>Réponses détaillées</h2>${table(["N°","Question","Réponse","Score"],(d.assessment_answers||[]).sort((a,b)=>a.question_id-b.question_id).map(x=>`<tr><td>${x.question_id}</td><td>${esc(x.question_text)}</td><td>${esc(x.answer_text)}</td><td>${x.score}</td></tr>`))}</article>`;
new Chart(document.querySelector("#detailRadar"),{type:"radar",data:{labels:dims.map(x=>x.dimension_name),datasets:[{label:"Évaluation",data:dims.map(x=>x.score),borderColor:"#25a9e0",backgroundColor:"rgba(37,169,224,.18)"}]},options:{responsive:true,maintainAspectRatio:false,scales:{r:{min:0,max:5}}}})}
async function reports(c){const d=await AdminApi.reports();c.innerHTML=`<article class="card"><h2>Rapports demandés</h2>${table(["Entreprise","Répondant","Score","Statut","Téléchargements","Date"],d.map(x=>`<tr><td>${esc(x.assessments?.companies?.name)}</td><td>${esc(x.assessments?.respondents?.first_name)} ${esc(x.assessments?.respondents?.last_name)}</td><td>${score(x.assessments?.global_score)}</td><td>${badge(x.status)}</td><td>${x.download_count||0}</td><td>${date(x.created_at)}</td></tr>`))}</article>`}
async function appointments(c){const d=await AdminApi.appointments();c.innerHTML=`<article class="card"><h2>Demandes de rendez-vous</h2>${table(["Entreprise","Contact","Créneau","Motif","Statut","Demande"],d.map(x=>`<tr><td>${esc(x.assessments?.companies?.name)}</td><td>${esc(x.assessments?.respondents?.first_name)} ${esc(x.assessments?.respondents?.last_name)}<br><small>${esc(x.assessments?.respondents?.email)}</small></td><td>${esc(x.appointment_date||"—")} ${esc(x.appointment_time||"")}</td><td>${esc(x.reason||"—")}</td><td>${badge(x.status)}</td><td>${date(x.created_at)}</td></tr>`))}</article>`}
async function activity(c){const d=await AdminApi.activity();c.innerHTML=`<article class="card"><h2>Activité récente</h2><div class="timeline">${d.map(x=>`<article><strong>${esc(x.event_type.replaceAll("_"," "))}</strong><p>${esc(x.companies?.name||"")} ${x.assessments?.global_score?`· score ${score(x.assessments.global_score)}`:""}</p><small>${date(x.created_at)}</small></article>`).join("")||'<p class="empty">Aucune activité.</p>'}</div></article>`}
async function settings(c){const cfg=window.FINASURE_SUPABASE_CONFIG;c.innerHTML=`<article class="card"><h2>Configuration</h2><div class="detail-grid"><div class="detail-item"><small>Projet Supabase</small>${esc(window.FinasureSupabase.configured?"Configuré":"À configurer")}</div><div class="detail-item"><small>URL publique</small>${esc(cfg?.url||"—")}</div><div class="detail-item"><small>Sécurité</small>RLS et authentification administrateur</div></div><p>Les comptes administrateurs sont gérés dans Supabase Auth puis autorisés dans la table <code>admin_users</code>. N’insérez jamais une clé <code>service_role</code> dans ce projet frontend.</p></article>`}
document.addEventListener("DOMContentLoaded",async()=>{try{const user=await AdminAuth.guard();if(!user)return;const active=page==="company"?"companies":page==="assessment"?"assessments":page,c=AdminLayout.mount(active,titles[page],user);c.innerHTML='<div class="loading">Chargement…</div>';await ({dashboard,companies,company,assessments,assessment,reports,appointments,activity,settings}[page]||dashboard)(c)}catch(e){const c=document.querySelector("#admin-content");if(c)error(c,e);console.error(e)}})
})();
